version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
       - ./mongoDB/db:/data/db
    ports:
        - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - database:db
  #   ports:
  #     - 8200:80

  # database:
  #   image: mariadb:10.1
  #   container_name: mariadb_madeication
  #   restart: always
  #   volumes:
  #     - ./mysql/initdb/:/docker-entrypoint-initdb.d
  #     - ./mysql/conf.d:/etc/mysql/conf.d
  #     - ./mysql/data/:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=docker
  #     - MYSQL_USER=sa
  #     - MYSQL_PASSWORD=sa

